import type { TestCatalogItem, TestCategory } from "./test-catalog";

/**
 * 테스트의 이름표.
 *
 * 목록 카드와 라우팅에 필요한 값만 담습니다. 문항과 결과 문구는 무거워서
 * lib/new-tests.ts 에 따로 두었습니다.
 *
 * 나누어 둔 이유가 있습니다. 예전에는 lib/test-catalog.ts 가 lib/new-tests.ts 를
 * import 했는데, 그러면 카탈로그를 쓰는 클라이언트 컴포넌트(TestDirectory,
 * GenericTestRunner, CrossPromo, TestGuide)가 20개 테스트의 문항 전체를 함께
 * 내려받았습니다. 방향을 뒤집어서, 이제 무거운 쪽이 가벼운 쪽을 참조합니다.
 *
 * 한 값은 한 곳에만 둡니다. 여기 있는 값은 lib/new-tests.ts 에 없고, 그 반대도
 * 마찬가지입니다. tests/test-catalog.test.mjs 가 둘이 어긋나지 않는지 봅니다.
 */
export type TestMeta = {
  slug: string;
  title: string;
  shortTitle: string;
  /** 페이지 상단의 영문 라벨. 카탈로그에는 안 쓰고 테스트 화면에서만 씁니다 */
  eyebrow: string;
  description: string;
  category: TestCategory;
  icon: string;
  color: string;
  keywords: string[];
  questionCount: number;
  duration: string;
};

/**
 * 순서가 곧 사이트맵과 generateStaticParams 의 순서입니다.
 * 마지막 hsp 는 문항을 손으로 쓴 테스트라 생성기를 거치지 않습니다.
 */
export const newTestMeta: TestMeta[] = [
  { slug: "love-tendency", title: "연애 성향 테스트", shortTitle: "연애 성향",
    eyebrow: "LOVE TENDENCY", category: "연애", icon: "♡", color: "#d56f8c",
    questionCount: 12, duration: "약 2분",
    description: "애정 표현과 관계에서 중요하게 생각하는 기준으로 나의 연애 성향을 확인합니다.",
    keywords: ["연애 성향 테스트", "연애 심리테스트", "나의 연애 성향"] },
  { slug: "spending-style", title: "소비 성향 테스트", shortTitle: "소비 성향",
    eyebrow: "SPENDING STYLE", category: "성격", icon: "₩", color: "#b58a4f",
    questionCount: 12, duration: "약 2분",
    description: "돈을 쓰는 순간의 기준과 만족 방식으로 나의 소비 패턴을 알아봅니다.",
    keywords: ["소비 성향 테스트", "소비 유형", "나의 소비 습관"] },
  { slug: "lazy-mbti", title: "게으름 MBTI 테스트", shortTitle: "게으름 MBTI",
    eyebrow: "LAZY MBTI", category: "성격", icon: "z", color: "#7868b4",
    questionCount: 12, duration: "약 2분",
    description: "일을 미루는 이유와 에너지를 회복하는 방식으로 나의 게으름 유형을 확인합니다.",
    keywords: ["게으름 MBTI 테스트", "게으름 유형", "미루기 테스트"] },
  { slug: "dating-style", title: "연애 스타일 테스트", shortTitle: "연애 스타일",
    eyebrow: "DATING STYLE", category: "연애", icon: "♥", color: "#c86486",
    questionCount: 12, duration: "약 2분",
    description: "연락, 데이트, 갈등 해결 방식에서 나타나는 나의 연애 스타일을 알아봅니다.",
    keywords: ["연애 스타일 테스트", "연애 유형 테스트", "연애 연락 스타일"] },
  { slug: "mbti-love-compatibility", title: "MBTI 연애 궁합 테스트", shortTitle: "MBTI 연애 궁합",
    eyebrow: "MBTI LOVE MATCH", category: "연애", icon: "∞", color: "#7865c4",
    questionCount: 12, duration: "약 2분",
    description: "관계에서 원하는 소통과 생활 방식을 바탕으로 나와 잘 맞는 MBTI 궁합 스타일을 찾습니다.",
    keywords: ["MBTI 연애 궁합 테스트", "MBTI 궁합", "MBTI 커플 궁합"] },
  { slug: "vegetable-village-character", title: "채소마을 캐릭터 테스트", shortTitle: "채소마을 캐릭터",
    eyebrow: "VEGGIE VILLAGE", category: "성격", icon: "♧", color: "#5c9568",
    questionCount: 12, duration: "약 2분",
    description: "일상 속 반응으로 나와 닮은 독창적인 채소마을 캐릭터를 찾아보세요.",
    keywords: ["채소 캐릭터 테스트", "캐릭터 성격 테스트", "재미있는 테스트"] },
  { slug: "friendship-symbol", title: "우리의 우정 징표 테스트", shortTitle: "우정 징표",
    eyebrow: "FRIENDSHIP SIGN", category: "성격", icon: "☆", color: "#5f8bb2",
    questionCount: 12, duration: "약 2분",
    description: "친구 사이에서 내가 맡는 역할과 우리 우정을 상징하는 징표를 확인합니다.",
    keywords: ["우정 테스트", "친구 관계 테스트", "우리의 우정 징표 테스트"] },
  { slug: "dont-get-hurt", title: "상처받지 마 테스트", shortTitle: "상처받지 마",
    eyebrow: "HEART SHIELD", category: "마음건강", icon: "◇", color: "#7b75b3",
    questionCount: 12, duration: "약 2분",
    description: "상처를 받는 순간의 반응과 나에게 필요한 마음 보호 방법을 알아봅니다.",
    keywords: ["상처받지 마 테스트", "감정 방어 테스트", "마음 보호 테스트"] },
  { slug: "animal-keeper", title: "동물 사육사 테스트", shortTitle: "동물 사육사",
    eyebrow: "ANIMAL KEEPER", category: "성격", icon: "♢", color: "#638b73",
    questionCount: 12, duration: "약 2분",
    description: "돌봄과 문제 해결 방식으로 나에게 어울리는 동물 사육사 유형을 찾습니다.",
    keywords: ["동물 사육사 테스트", "동물 성격 테스트", "직업 성향 테스트"] },
  { slug: "family-letter-personality", title: "가정통신문 성격 테스트", shortTitle: "가정통신문 성격",
    eyebrow: "SCHOOL LETTER", category: "성격", icon: "□", color: "#7686ad",
    questionCount: 12, duration: "약 2분",
    description: "학창 시절 가정통신문을 대하는 모습으로 알아보는 재미형 성격 테스트입니다.",
    keywords: ["가정통신문 성격 테스트", "학창시절 성격 테스트", "재미있는 심리테스트"] },
  { slug: "christmas-cookie-personality", title: "크리스마스 쿠키 성격 테스트", shortTitle: "쿠키 성격",
    eyebrow: "CHRISTMAS COOKIE", category: "성격", icon: "✦", color: "#b4675b",
    questionCount: 12, duration: "약 2분",
    description: "연말을 보내는 취향으로 나와 닮은 크리스마스 쿠키 캐릭터를 찾아보세요.",
    keywords: ["크리스마스 쿠키 성격 테스트", "연말 심리테스트", "쿠키 캐릭터 테스트"] },
  { slug: "personality-guide", title: "남녀 성격 풀이법 테스트", shortTitle: "성격 풀이법",
    eyebrow: "PERSONALITY GUIDE", category: "성격", icon: "↔", color: "#657fa4",
    questionCount: 12, duration: "약 2분",
    description: "성별을 단정하지 않고 말과 행동을 해석하는 방식으로 나의 소통 성격을 확인합니다.",
    keywords: ["남자 성격 풀이법", "여자 성격 풀이법", "성격 해석 테스트"] },
  { slug: "couple-character", title: "커플 캐릭터 테스트", shortTitle: "커플 캐릭터",
    eyebrow: "COUPLE CHARACTER", category: "연애", icon: "♧", color: "#cf6f8b",
    questionCount: 12, duration: "약 2분",
    description: "연애할 때 나타나는 행동으로 나의 커플 캐릭터와 관계 속 역할을 확인합니다.",
    keywords: ["커플 캐릭터 테스트", "연애 캐릭터 테스트", "커플 성격 테스트"] },
  { slug: "f-flirting-simulation", title: "F썸녀·F썸남 꼬시기 시뮬레이션", shortTitle: "F썸 시뮬레이션",
    eyebrow: "F FLIRTING SIMULATION", category: "연애", icon: "F", color: "#bd6f9c",
    questionCount: 12, duration: "약 2분",
    description: "공감형 썸 상대와의 상황 선택을 통해 나의 호감 표현 방식을 확인합니다.",
    keywords: ["F썸녀 꼬시기", "F썸남 꼬시기", "썸 시뮬레이션", "연애 시뮬레이션"] },
  { slug: "healing-sprite", title: "힐링 요정 성격 테스트", shortTitle: "힐링 요정",
    eyebrow: "HEALING SPRITE", category: "마음건강", icon: "✧", color: "#689b83",
    questionCount: 12, duration: "약 2분",
    description: "지친 일상을 회복하는 방식으로 나와 닮은 독창적인 힐링 요정 캐릭터를 찾습니다.",
    keywords: ["힐링 캐릭터 테스트", "힐링 요정 테스트", "마음 회복 테스트"] },
  { slug: "self-reflection", title: "자아 성찰 성격 테스트", shortTitle: "자아 성찰",
    eyebrow: "SELF REFLECTION", category: "마음건강", icon: "○", color: "#6e75aa",
    questionCount: 12, duration: "약 2분",
    description: "생각과 감정을 돌아보는 방식으로 나의 자아 성찰 유형을 확인합니다.",
    keywords: ["자아 성찰 성격 테스트", "자기 성찰 테스트", "나를 알아보는 테스트"] },
  { slug: "first-impression", title: "첫인상 테스트", shortTitle: "첫인상",
    eyebrow: "FIRST IMPRESSION", category: "성격", icon: "◎", color: "#6b83b2",
    questionCount: 12, duration: "약 2분",
    description: "처음 만난 자리에서 드러나는 말투와 행동으로 사람들이 느끼는 나의 첫인상을 확인합니다.",
    keywords: ["첫인상 테스트", "나의 첫인상", "첫인상 성격 테스트"] },
  { slug: "future-person", title: "미래인 테스트", shortTitle: "미래인",
    eyebrow: "FUTURE PERSON", category: "성격", icon: "△", color: "#587fa5",
    questionCount: 12, duration: "약 2분",
    description: "변화와 기술, 새로운 가능성을 대하는 태도로 나의 미래인 유형을 알아봅니다.",
    keywords: ["미래인 테스트", "미래 성향 테스트", "미래의 나 테스트"] },
  { slug: "love-ability", title: "연애 능력 테스트", shortTitle: "연애 능력",
    eyebrow: "LOVE ABILITY", category: "연애", icon: "+", color: "#cb6d89",
    questionCount: 12, duration: "약 2분",
    description: "공감, 표현, 갈등 해결, 관계 유지에서 현재 나의 연애 강점을 확인합니다.",
    keywords: ["연애 능력 테스트", "연애 잘하는 법", "연애 심리테스트"] },
  { slug: "neujoh", title: "느좋 테스트", shortTitle: "느좋",
    eyebrow: "NEUJOH POINT", category: "성격", icon: "✧", color: "#c98bb5",
    questionCount: 12, duration: "약 2분",
    description: "사람들이 나에게서 느낌이 좋다고 느끼는 지점이 어디인지 확인합니다.",
    keywords: ["느좋 테스트", "느좋 뜻", "분위기 테스트", "매력 테스트"] },
  { slug: "hyeonta", title: "현타 지수 테스트", shortTitle: "현타 지수",
    eyebrow: "REALITY CHECK", category: "마음건강", icon: "◍", color: "#6b7a99",
    questionCount: 12, duration: "약 2분",
    description: "요즘 나에게 현타가 오는 순간과 그 이유가 어디에 있는지 짚어봅니다.",
    keywords: ["현타 테스트", "현타 뜻", "번아웃 테스트", "무기력 테스트"] },
  { slug: "dopamine-addiction", title: "도파민 중독 테스트", shortTitle: "도파민 중독",
    eyebrow: "DOPAMINE CHECK", category: "마음건강", icon: "▶", color: "#d9614f",
    questionCount: 12, duration: "약 2분",
    description: "숏폼과 알림에 얼마나 길들여졌는지, 어떤 자극에 약한지 확인합니다.",
    keywords: ["도파민 중독 테스트", "숏폼 중독", "스마트폰 중독 테스트", "도파민 디톡스"] },
  { slug: "autumn-bti", title: "가을BTI 테스트", shortTitle: "가을BTI",
    eyebrow: "AUTUMN BTI", category: "성격", icon: "❉", color: "#c2763f",
    questionCount: 12, duration: "약 2분",
    description: "가을을 보내는 방식으로 알아보는 나의 계절 성향을 확인합니다.",
    keywords: ["가을BTI", "가을 테스트", "가을 성격 테스트", "계절 심리테스트"] },
  { slug: "chuseok-food", title: "추석 음식 테스트", shortTitle: "추석 음식",
    eyebrow: "CHUSEOK FOOD", category: "성격", icon: "☾", color: "#c98a3f",
    questionCount: 12, duration: "약 2분",
    description: "명절 상 앞에서 손이 먼저 가는 음식으로 알아보는 나의 성격 유형입니다.",
    keywords: ["추석 테스트", "추석 음식 테스트", "명절 심리테스트", "송편 테스트"] },
  { slug: "holiday-stress", title: "명절 스트레스 테스트", shortTitle: "명절 스트레스",
    eyebrow: "HOLIDAY STRESS", category: "마음건강", icon: "◒", color: "#8a6a7d",
    questionCount: 12, duration: "약 2분",
    description: "명절에 나를 가장 지치게 하는 지점이 어디인지 확인합니다.",
    keywords: ["명절 스트레스 테스트", "명절 증후군", "추석 스트레스", "명절 스트레스 자가진단"] },
  { slug: "aura", title: "나의 아우라 찾기", shortTitle: "아우라",
    eyebrow: "MY AURA", category: "성격", icon: "✺", color: "#8f6fd0",
    questionCount: 12, duration: "약 2분",
    description: "사람들이 나에게서 느끼는 분위기, 나의 아우라 색을 찾습니다.",
    keywords: ["아우라 테스트", "나의 아우라", "아우라 색깔 테스트", "분위기 테스트"] },
  { slug: "my-color", title: "나만의 컬러 찾기", shortTitle: "나만의 컬러",
    eyebrow: "MY COLOR", category: "성격", icon: "◉", color: "#4f8fb5",
    questionCount: 12, duration: "약 2분",
    description: "나를 한 가지 색으로 표현하면 무슨 색일지 12문항으로 찾습니다.",
    keywords: ["나만의 컬러 테스트", "성격 색깔 테스트", "컬러 심리테스트", "나의 색깔"] },
  { slug: "destiny-animal", title: "운명의 동물 테스트", shortTitle: "운명의 동물",
    eyebrow: "DESTINY ANIMAL", category: "성격", icon: "❋", color: "#5f8f9f",
    questionCount: 12, duration: "약 2분",
    description: "관계와 혼자만의 시간을 대하는 방식으로 나와 닮은 동물을 찾습니다.",
    keywords: ["운명의 동물 테스트", "동물 성격 테스트", "나와 닮은 동물", "동물상 테스트"] },
  { slug: "four-cut", title: "성격 네컷 테스트", shortTitle: "성격 네컷",
    eyebrow: "FOUR CUT", category: "성격", icon: "▤", color: "#d1607f",
    questionCount: 12, duration: "약 2분",
    description: "네 컷 사진을 찍을 때 나오는 행동으로 알아보는 나의 성격 유형입니다.",
    keywords: ["성격 네컷 테스트", "인생네컷 테스트", "네컷 성격", "사진 성격 테스트"] },
  { slug: "halloween", title: "핼러윈 캐릭터 테스트", shortTitle: "핼러윈 캐릭터",
    eyebrow: "HALLOWEEN", category: "성격", icon: "◑", color: "#d9834f",
    questionCount: 12, duration: "약 2분",
    description: "핼러윈 밤에 어울리는 나의 캐릭터를 성격으로 찾아봅니다.",
    keywords: ["핼러윈 테스트", "할로윈 테스트", "핼러윈 캐릭터", "핼러윈 성격테스트"] },
  { slug: "suneung-mental", title: "수능 D-day 멘탈 테스트", shortTitle: "수능 멘탈",
    eyebrow: "D-DAY MENTAL", category: "마음건강", icon: "✎", color: "#5d8b83",
    questionCount: 12, duration: "약 2분",
    description: "시험을 앞두고 내 멘탈이 어떤 방식으로 버티는지 확인합니다.",
    keywords: ["수능 멘탈 테스트", "시험 불안 테스트", "수능 심리테스트", "시험 멘탈관리"] },
  { slug: "pepero", title: "빼빼로데이 테스트", shortTitle: "빼빼로데이",
    eyebrow: "PEPERO DAY", category: "연애", icon: "▮", color: "#b05c4a",
    questionCount: 12, duration: "약 2분",
    description: "빼빼로를 고르고 건네는 방식으로 알아보는 나의 마음 표현법입니다.",
    keywords: ["빼빼로데이 테스트", "빼빼로 테스트", "11월 11일 테스트", "선물 성향 테스트"] },
  { slug: "first-snow", title: "첫눈 연애 테스트", shortTitle: "첫눈 연애",
    eyebrow: "FIRST SNOW", category: "연애", icon: "❄", color: "#7f9fc4",
    questionCount: 12, duration: "약 2분",
    description: "첫눈이 오는 날 내가 어떤 사람이 되는지로 연애 성향을 봅니다.",
    keywords: ["첫눈 테스트", "첫눈 연애 테스트", "겨울 연애 테스트", "겨울 심리테스트"] },
  { slug: "christmas-santa", title: "크리스마스 산타 유형 테스트", shortTitle: "산타 유형",
    eyebrow: "SANTA TYPE", category: "성격", icon: "✦", color: "#c4544f",
    questionCount: 12, duration: "약 2분",
    description: "크리스마스를 준비하는 방식으로 알아보는 나의 산타 유형입니다.",
    keywords: ["크리스마스 테스트", "산타 유형 테스트", "크리스마스 심리테스트", "크리스마스 성격테스트"] },
  { slug: "christmas-love", title: "크리스마스 연애 테스트", shortTitle: "크리스마스 연애",
    eyebrow: "CHRISTMAS LOVE", category: "연애", icon: "♥", color: "#c4544f",
    questionCount: 12, duration: "약 2분",
    description: "크리스마스를 누구와 어떻게 보내고 싶은지로 연애 성향을 봅니다.",
    keywords: ["크리스마스 연애 테스트", "크리스마스 커플 테스트", "연말 연애운", "크리스마스 데이트"] },
  { slug: "year-end-party", title: "연말 송년회 캐릭터 테스트", shortTitle: "송년회 캐릭터",
    eyebrow: "YEAR END PARTY", category: "성격", icon: "▽", color: "#5f8fa8",
    questionCount: 12, duration: "약 2분",
    description: "송년회 자리에서 내가 맡게 되는 역할로 성격을 알아봅니다.",
    keywords: ["송년회 테스트", "연말 모임 테스트", "회식 유형 테스트", "모임 성격 테스트"] },
  { slug: "new-year-resolution", title: "새해 다짐 유형 테스트", shortTitle: "새해 다짐",
    eyebrow: "NEW YEAR", category: "성격", icon: "◔", color: "#5f7fa8",
    questionCount: 12, duration: "약 2분",
    description: "새해 목표를 세우고 지키는 방식으로 나의 실행 유형을 확인합니다.",
    keywords: ["새해 다짐 테스트", "새해 목표 테스트", "신년 계획 테스트", "목표 실행 유형"] },
  { slug: "bungeoppang", title: "붕어빵 테스트", shortTitle: "붕어빵",
    eyebrow: "BUNGEOPPANG", category: "성격", icon: "◗", color: "#a4544f",
    questionCount: 12, duration: "약 2분",
    description: "어떤 붕어빵에 손이 가는지로 알아보는 나의 성격 유형입니다.",
    keywords: ["붕어빵 테스트", "팥붕 슈붕", "겨울 간식 테스트", "붕어빵 성격테스트"] },
  { slug: "godsaeng", title: "갓생력 테스트", shortTitle: "갓생력",
    eyebrow: "GODSAENG POWER", category: "성격", icon: "☀", color: "#e08a3c",
    questionCount: 12, duration: "약 2분",
    description: "하루를 굴러가게 만드는 방식으로 내가 어떤 힘으로 갓생을 사는지 확인합니다.",
    keywords: ["갓생 테스트", "갓생력 테스트", "갓생 뜻", "루틴 테스트"] },
  { slug: "jjinchin", title: "찐친 테스트", shortTitle: "찐친",
    eyebrow: "REAL FRIEND", category: "성격", icon: "◎", color: "#4f8fa8",
    questionCount: 12, duration: "약 2분",
    description: "친구 사이에서 내가 어떤 방식으로 가까워지고 오래 가는지 확인합니다.",
    keywords: ["찐친 테스트", "찐친 뜻", "반모 테스트", "친구 관계 테스트"] },
  { slug: "gwanjong", title: "관종 지수 테스트", shortTitle: "관종 지수",
    eyebrow: "SPOTLIGHT INDEX", category: "성격", icon: "◉", color: "#d9683f",
    questionCount: 12, duration: "약 2분",
    description: "주목받고 싶은 마음이 나에게서 어느 쪽으로 향하는지 확인합니다.",
    keywords: ["관종 테스트", "관종 지수 테스트", "관종 뜻", "인정 욕구 테스트"] },
  { slug: "sonjeol", title: "손절각 테스트", shortTitle: "손절각",
    eyebrow: "CUT-OFF POINT", category: "마음건강", icon: "◈", color: "#8a6a9e",
    questionCount: 12, duration: "약 2분",
    description: "관계가 힘들어질 때 내가 어떤 방식으로 거리를 정하는지 확인합니다.",
    keywords: ["손절 테스트", "손절각 뜻", "인간관계 정리", "관계 스트레스 테스트"] },
  { slug: "hsp", title: "HSP 테스트", shortTitle: "HSP 테스트",
    eyebrow: "HIGHLY SENSITIVE PERSON", category: "마음건강", icon: "◈", color: "#5f6fb0",
    questionCount: 16, duration: "약 3분",
    description: "16문항으로 감각 처리 민감성의 네 갈래 중 나에게 두드러지는 방향을 확인합니다.",
    keywords: ["HSP 테스트", "매우 예민한 사람", "예민함 테스트", "감각 처리 민감성"] },
  { slug: "egen-teto-male", title: "에겐남·테토남 테스트", shortTitle: "에겐남·테토남",
    eyebrow: "EGEN · TETO FOR MEN", category: "성격", icon: "◑", color: "#f2603c",
    questionCount: 20, duration: "약 3분",
    description: "20문항으로 에겐남·테토남은 물론, 겉과 속이 다른 두 유형까지 네 가지 중 나를 찾습니다.",
    keywords: ["에겐남 테스트", "테토남 테스트", "에겐남 테토남", "에겐테토 남자", "테토남 특징", "에겐남 특징"] },
];

const bySlug = new Map(newTestMeta.map((meta) => [meta.slug, meta]));

export function testMeta(slug: string): TestMeta {
  const meta = bySlug.get(slug);
  if (!meta) throw new Error(`lib/test-meta.ts 에 ${slug} 항목이 없습니다.`);
  return meta;
}

export const newTestCatalog: TestCatalogItem[] = newTestMeta.map((meta) => ({
  slug: meta.slug,
  title: meta.title,
  shortTitle: meta.shortTitle,
  description: meta.description,
  category: meta.category,
  questionCount: meta.questionCount,
  duration: meta.duration,
  icon: meta.icon,
  color: meta.color,
  href: `/tests/${meta.slug}/`,
  status: "published",
  keywords: meta.keywords,
}));

export const newTestSlugs = newTestMeta.map((meta) => meta.slug);
